# Generated by Django 5.1.5 on 2025-01-24 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_user_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.machine', verbose_name='Машина'),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.machine', verbose_name='Машина'),
        ),
    ]
