# Generated by Django 5.1.5 on 2025-01-24 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_complaints_machine_alter_maintenance_machine'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EquimentModel',
            new_name='EquipmentModel',
        ),
    ]
