# Generated by Django 5.1.5 on 2025-01-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_rename_equimentmodel_equipmentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaints',
            name='date_of_refusal',
            field=models.DateTimeField(max_length=120, verbose_name='Дата отказа'),
        ),
    ]
