# Generated by Django 5.1.5 on 2025-01-26 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_client_user_servicecompany_user_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancetype',
            options={'verbose_name': 'Вид ТО', 'verbose_name_plural': 'Виды ТО'},
        ),
        migrations.AlterModelOptions(
            name='servicecompany',
            options={'verbose_name': 'Сервисная компания', 'verbose_name_plural': 'Сервисные компании'},
        ),
    ]
